### ISSUE TITLE
Create and Edit Campaign Step 1

### ISSUE THREAD

**Issue by 1finedev** [abeg-help/backend#129]
# Issue Template

## Issue Type

- [ ] Bug Report
- [x] Feature Request
- [ ] Enhancement
- [ ] Other (Please specify)

## Description

We have split the campaign creation into multiple steps, hence this should be a file inside of 

```
controllers
          campaign
               create
                    stepOne
```

## Details

This would cover the following parts

What best describes your fundraiser? 
What country are you located?
Campaign Tags?

**Note:** Please make sure to follow the project's code of conduct and contribution guidelines when creating an issue. Thank you for contributing to our open-source project!

**Comment by JC-Coder** [comment]
.take

**Comment by Hydradaboss** [comment]
.take
