### ISSUE TITLE
Create And Edit Campaign Step 2

### ISSUE THREAD

**Issue by 1finedev** [abeg-help/backend#130]
# Issue Template

## Issue Type

- [ ] Bug Report
- [x] Feature Request
- [ ] Enhancement
- [ ] Other (Please specify)

## Description

We have split the campaign creation into multiple steps, hence this should be a file inside of 

```
controllers
          campaign
               create
                    stepTwo
```

## Details

This would cover the following parts

Campaign Title
Who is fundraising
Campaign Goal
Campaign Deadline

**Note:** Please make sure to follow the project's code of conduct and contribution guidelines when creating an issue. Thank you for contributing to our open-source project!

**Comment by Davheed2** [comment]
.take
