### ISSUE TITLE
Create queue to automatically process created campaign

### ISSUE THREAD

**Issue by 1finedev** [abeg-help/backend#132]
# Issue Template

## Issue Type

- [ ] Bug Report
- [x] Feature Request
- [ ] Enhancement
- [ ] Other (Please specify)

## Description

Newly Created / Edited campaigns will have to go through an automated or manual review process
This task would handle the automated review process by picking campaigns from queues and running them through a couple of iterations 

Predefined ones are listed below 
1. Filter and check for inappropriate content, including vulgar language, nudity, or other potentially offensive words
2. Strip out media metadata to avoid unintentionally opening up users to doxxing 
3. filter media to avoid adult content, gore or sensitive content being posted
4. Tokenize and compare content with campaign title to see if they match etc
5. Spell / grammar check 
6. Plagiarism detector
7. Duplicate fundraising detector

and lots more

## Details
We will take advantage of NLP, AI etc and npm packages like `bad-words`, `natural`, `compromise` etc

**Note:** Please make sure to follow the project's code of conduct and contribution guidelines when creating an issue. Thank you for contributing to our open-source project!

**Comment by JC-Coder** [comment]
.take
