### ISSUE TITLE
Delete Campaign

### ISSUE THREAD

**Issue by 1finedev** [abeg-help/backend#135]
# Issue Template

## Issue Type

- [ ] Bug Report
- [ ] Feature Request
- [ ] Enhancement
- [ ] Other (Please specify)

## Description

Allow deletion of created campaign if it has not been published / has not received donations yet!

**Note:** Please make sure to follow the project's code of conduct and contribution guidelines when creating an issue. Thank you for contributing to our open-source project!

**Comment by Davheed2** [comment]
.take
