### ISSUE TITLE
Registration Endpoint for User Account

### ISSUE THREAD

**Issue by JC-Coder** [abeg-help/backend#39]
# Issue Template

## Issue Type

- [ ] Bug Report
- [ ] Feature Request
- [x] Enhancement
- [ ] Other (Please specify)

## Description
Develop a registration endpoint that allows users to create an account with the required information while incorporating the "zod" library for input validation.

## Details
1. Design the API endpoint for user registration.
2. Implement input validation for user data.
3. Store user information in the database.
4. default role for user should be "user"

Here is the user schema : 
1. Photo 
2. firstName 
3. lastName 
4. email 
5. phoneNumber
6. Password 
7. isGoogleAccount
8. role 
9. isEmailVerified

**Comment by Klin-Coders** [comment]
Issue seems vague, kindly create a new issue with well written process or re-open and edit
