### ISSUE TITLE
Implement Local Sign In Functionality

### ISSUE THREAD

**Issue by JC-Coder** [abeg-help/backend#40]
# Issue Template

## Issue Type

- [ ] Bug Report
- [x] Feature Request
- [ ] Enhancement
- [ ] Other (Please specify)

## Description

Create the backend functionality for users to login using their email and password

## Details
1. implement login and also include refreshTokens using jwt 
2. validate user input using zod 
3. upon login return the user , token and refreshToken

**Comment by Klin-Coders** [comment]
Issue seems vague, kindly create a new issue with well written process or re-poen and edit
