### ISSUE TITLE
Get Profile Functionality

### ISSUE THREAD

**Issue by JC-Coder** [abeg-help/backend#41]
# Issue Template

## Issue Type

- [ ] Bug Report
- [ ] Feature Request
- [x] Enhancement
- [ ] Other (Please specify)

## Description
Provide endpoint for user to get their profile details

## Details
Provide endpoint for user to get their profile details

**Comment by Klin-Coders** [comment]
Issue seems vague, kindly create a new issue with well written process or re-poen and edit
