### ISSUE TITLE
Update profile functionality

### ISSUE THREAD

**Issue by JC-Coder** [abeg-help/backend#42]
# Issue Template

## Issue Type

- [ ] Bug Report
- [ ] Feature Request
- [x] Enhancement
- [ ] Other (Please specify)

## Description
Add endpoint for user to update their profile details 

## Details
The following user details can be updated 
names and phone number . 
use zod to validate input

**Comment by Klin-Coders** [comment]
Issue seems vague, kindly create a new issue with well written process or re-poen and edit
