### ISSUE TITLE
Add email send handler

### ISSUE THREAD

**Issue by JC-Coder** [abeg-help/backend#43]
# Issue Template

## Issue Type

- [ ] Bug Report
- [ ] Feature Request
- [x] Enhancement
- [ ] Other (Please specify)

## Description
Add a helper function to enable email sending . use nodemailer and gmail smtp to setup

## Details
Add a helper function to enable email sending . use nodemailer and gmail smtp to setup

**Comment by CyberVerse2** [comment]
Assign

**Comment by Klin-Coders** [comment]
@CyberVerse2  you already forgot the command to assign tasks to yourself?
