### ISSUE TITLE
Update password functionality

### ISSUE THREAD

**Issue by JC-Coder** [abeg-help/backend#44]
# Issue Template

## Issue Type

- [ ] Bug Report
- [ ] Feature Request
- [x] Enhancement
- [ ] Other (Please specify)

## Description
Endpoint for authenticated user to change their password.

## Details
Provide an endpoint for user to change their password. 
user is to provide oldPassword , newPassword and confirmPassword . 
use zod for input validation and ensure password has a min length of 8 characters including uppercase , lowercase and symbol .

## Reproduction Steps (For Bug Reports)

1. [Step 1]
2. [Step 2]
3. [Step 3]

## Expected Behavior (For Bug Reports)

[Describe what you expected to happen.]

## Actual Behavior (For Bug Reports)

[Describe what actually happened.]

## Additional Information

[Include any additional information that may help in resolving the issue, such as screenshots, logs, or any related links.]

## Would you like to contribute to fixing this issue?

- [ ] Yes
- [ ] No

## Related Pull Requests (if any)

[Link to any related pull requests, if applicable.]

## Failure Logs

Please include any relevant log snippets or files here.

**Note:** Please make sure to follow the project's code of conduct and contribution guidelines when creating an issue. Thank you for contributing to our open-source project!

**Comment by Klin-Coders** [comment]
Issue seems vague, kindly create a new issue with well written process or re-poen and edit
