### ISSUE TITLE
Feat: Setup controller and route for signup

### ISSUE THREAD

**Issue by 289Volts** [abeg-help/backend#48]
## Issue Type

- [ ] Bug Report
- [X] Feature Request
- [ ] Enhancement
- [ ] Other (Please specify)

## Description

For the authentication process, a route and controller is required to sign up endpoint

## Details

Using the existing file structure, create a controller and route for the sign up endpoint. These will be tested with the mock UI that the frontend devs will provide

## Additional Information

To resolve this issue, 
1. create a folder in the controllers and route folder which will contain your file. 
2. Export files and import them in the index file of the controller and route folder

## Would you like to contribute to fixing this issue?

- [ ] Yes
- [ ] No

**Note:** Please make sure to follow the project's code of conduct and contribution guidelines when creating an issue. Thank you for contributing to our open-source project!

**Comment by Toyin5** [comment]
.take
