### ISSUE TITLE
Chore: Design a user schema

### ISSUE THREAD

**Issue by 289Volts** [abeg-help/backend#49]
## Issue Type

- [ ] Bug Report
- [ ] Feature Request
- [X] Enhancement
- [ ] Other (Please specify)

## Description

The existing user schema is incomplete as it is still missing some necessary fields.

## Details

We'll need more information about the user than what is currently in the user schema hence the reason for creating this issue. 

## Additional Information

To resolve this issue, 
1. Navigate to `src/schemas/user.schema.ts`
2. Edit the file and add the necessary fields.
3. Save changes and request review

## Would you like to contribute to fixing this issue?

- [ ] Yes
- [ ] No

**Note:** Please make sure to follow the project's code of conduct and contribution guidelines when creating an issue. Thank you for contributing to our open-source project!

**Comment by Chimise** [comment]
.take

**Comment by Ryan-Zayne** [comment]
.take
