### ISSUE TITLE
Create controller for user sign-in/login

### ISSUE THREAD

**Issue by Chimise** [abeg-help/backend#68]
# Issue Template

## Issue Type

- [ ] Bug Report
- [x] Feature Request
- [ ] Enhancement
- [ ] Other (Please specify)

## Description

The users need to login or signin in order to get the required permission to interact with the app.

## Details

The signin controller needs to do the following:
- Check the entered user credentials to ensure that they are valid
- Generate authentication tokens 
- Update required user state
- Send the user data

## Reproduction Steps (For Bug Reports)

1. [Step 1]
2. [Step 2]
3. [Step 3]

## Expected Behavior (For Bug Reports)

[Describe what you expected to happen.]

## Actual Behavior (For Bug Reports)

[Describe what actually happened.]

## Additional Information

[Include any additional information that may help in resolving the issue, such as screenshots, logs, or any related links.]

## Would you like to contribute to fixing this issue?

- [ ] Yes
- [ ] No

## Related Pull Requests (if any)

[Link to any related pull requests, if applicable.]

## Failure Logs

Please include any relevant log snippets or files here.

**Note:** Please make sure to follow the project's code of conduct and contribution guidelines when creating an issue. Thank you for contributing to our open-source project!

**Comment by Chimise** [comment]
.take

**Comment by Unknown3850** [comment]
Well according to your pm I was dumb not to understand this code lol and I was able to spot the bugs  in the app error well there's another bug lmao and I will only tell you guys if he apologize and more he was showing you all a transpired code in the public repo that shows how dumb he is I can't believe you have experience wirh js and you couldn't write a clean code not even a single oop just function calling function lol

**Comment by Unknown3850** [comment]
He fixed the app error well thanks to me but I won't tell you guys another bugs that I spotted
