### ISSUE TITLE
Edit user profile details

### ISSUE THREAD

**Issue by 1finedev** [abeg-help/backend#97]
# Issue Template

## Issue Type

- [ ] Bug Report
- [x] Feature Request
- [x] Enhancement
- [ ] Other (Please specify)

## Description

This is an endpoint to change a user basic information.

please note this must not allow changing of sensitive info like `passwords` or `bank account details` and others

**Comment by Vkeybhoi** [comment]
Taken

**Comment by Hydradaboss** [comment]
.take
